version: "3.8"
services:
  microservicio_smith_api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: microservicio_smith
    image: smith/backend:latest
    restart: on-failure
    ports:
      - "4173:4173"
    networks:
      - mc_network

networks:
  mc_network:
    driver: bridge
