import { defineConfig } from 'vite';

export default defineConfig({
  // ...existing code...
  preview: {
    // ...existing code...
    allowedHosts: [
      // ...existing hosts...
      "smithzea.com"
    ]
    // ...existing code...
  }
  // ...existing code...
});